import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Navbar from "@/components/Navbar";
import { BiSearch } from "react-icons/bi";
import {
  AiOutlineLeftCircle,
  AiOutlineRightCircle,
  AiOutlineTwitter,
} from "react-icons/ai";
import { TbMathSymbols, TbPlant } from "react-icons/tb";
import { HiOutlineComputerDesktop } from "react-icons/hi2";
import {
  FaMicroscope,
  FaUserGraduate,
  FaFacebookF,
  FaLinkedinIn,
} from "react-icons/fa";
import { MdPrivateConnectivity } from "react-icons/md";
import { BsGraphUp } from "react-icons/bs";
import { GiTakeMyMoney } from "react-icons/gi";
import { FiInstagram } from "react-icons/fi";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Simple Classroom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="home-page-wrapper"></div>
        <div className="mt-[-100vh]">
          <Navbar />
          <section
            id=""
            className="text-white flex flex-col justify-center items-center h-[89vh]"
          >
            <p className="text-3xl font-extrabold max-w-[500px] text-center">
              Find the best tutors that match your need
            </p>
            <p className="text-xl py-6">Lorem ipsum dolor amet</p>
            <div className="relative">
              <BiSearch className="absolute top-2 left-3" />
              <input
                type="text"
                className="rounded-[50px] border border-white bg-transparent pl-9 px-3 py-2 w-fit text-xs font-thin placeholder:text-white relative z-10"
                placeholder="Search for subjects, tutors"
              />
            </div>
          </section>
          <section
            id="2"
            className="text-white flex md:flex-wrap md:justify-center flex-col md:flex-row items-center lg:gap-28 md:gap-16 gap-10 min-h-[368px]"
          >
            <div className="">
              <Image
                src={"/../public/Home-1.jpg"}
                height={300}
                width={300}
                className="h-[200px] w-[300px] object-cover rounded-lg"
              />
              <div className="py-8">
                <p className="font-bold pb-3 text-lg">Daily live classes</p>
                <p className="text-xs text-white/75 w-[300px]">
                  Velit excepteur nulla fugiat eu cillum do Lorem laborum ipsum.
                  Fugiat voluptate nulla elit sunt. Elit dolor commodo veniam
                  nostrud non in proident est consectetur consequat.
                </p>
              </div>
            </div>
            <div className="">
              <Image
                src={"/../public/home-2.jpg"}
                height={300}
                width={300}
                className="h-[200px] w-[300px] object-cover rounded-lg"
              />
              <div className="py-8">
                {" "}
                <p className="font-bold pb-3 text-lg">Practice and Revise</p>
                <p className="text-xs text-white/75 w-[300px]">
                  Velit excepteur nulla fugiat eu cillum do Lorem laborum ipsum.
                  Fugiat voluptate nulla elit sunt. Elit dolor commodo veniam
                  nostrud non in proident est consectetur consequat.
                </p>
              </div>
            </div>
            <div className="">
              <Image
                src={"/../public/home-3.jpg"}
                height={300}
                width={300}
                className="h-[200px] w-[300px] object-cover rounded-lg"
              />
              <div className="py-8">
                <p className="font-bold pb-3 text-lg">
                  Learn anytime, Anywhere
                </p>
                <p className="text-xs text-white/75 w-[300px]">
                  Velit excepteur nulla fugiat eu cillum do Lorem laborum ipsum.
                  Fugiat voluptate nulla elit sunt. Elit dolor commodo veniam
                  nostrud non in proident est consectetur consequat.
                </p>
              </div>
            </div>
          </section>
          <section className="bg-indigo-800 text-white flex justify-around items-center h-[80px] px-32 text-sm">
            <div>
              <AiOutlineLeftCircle className="h-[25px] w-[25px]" />
            </div>
            <div className="flex flex-1 justify-around px-10 gap-5 md:gap-0">
              <span className="md:flex hidden">
                <TbMathSymbols className="h-[20px] w-[20px] mr-2" />
                Mathematics
              </span>
              <span className="lg:flex hidden">
                <TbPlant className="h-[20px] w-[20px] mr-2" />
                Botany
              </span>
              <span className="flex">
                <FaMicroscope className="h-[20px] w-[20px] mr-2" />
                Biology
              </span>
              <span className="flex">
                <HiOutlineComputerDesktop className="h-[20px] w-[20px] mr-2" />
                Computer
              </span>
            </div>
            <div>
              <AiOutlineRightCircle className="h-[25px] w-[25px]" />
            </div>
          </section>
          <section className="bg-white flex flex-col items-center lg:px-32 md:px-16 px-6 text-sm s">
            <div className="pt-32 ">
              <p className="text-3xl font-bold">Enhance your Learning skills</p>
              <p className="md:w-[420px] w-[300px] md:text-center pt-4 text-black/75">
                Ea ut eiusmod dolore dolor do in nulla do nisi. Sunt est sint
                sit elit adipisicing mollit ad mollit laboris qui commodo. Magna
                labore occaecat minim ullamco est ullamco.
              </p>
            </div>
            <div className="lg:py-32 md:py-16 py-12 flex justify-around w-full flex-wrap gap-10 xl:gap-0">
              <div className="p-5 rounded-xl bg-gradient-to-b from-purple-500 to-violet-500 text-white w-[225px] h-[250px] flex flex-col justify-around items-center gap-5 shadow-lg shadow-purple-300">
                <div>
                  <FaUserGraduate size={55} className="mt-8" />
                </div>
                <div>
                  <p className="text-center mb-3 font-bold">Best Tutors</p>
                  <p className="text-[9px] leading-3 text-center text-white/75">
                    Dolore cillum ipsum sint amet minim tempor officia amet
                    tempor. Ex exercitation irure ullamco veniam et cupidatat
                    cillum sint esse labore ad. Dolore velit tempor deserunt
                    consectetur qui Lorem amet deserunt.
                  </p>
                </div>
              </div>
              <div className="p-5 rounded-xl bg-gradient-to-b from-purple-500 to-violet-500 text-white w-[225px] h-[250px] flex flex-col justify-around items-center gap-5 shadow-lg shadow-purple-300">
                <div>
                  <MdPrivateConnectivity size={55} className="mt-8" />
                </div>
                <div>
                  <p className="text-center mb-3 font-bold">Personalised</p>
                  <p className="text-[9px] leading-3 text-center text-white/75">
                    Amet nostrud esse ullamco exercitation esse. Cupidatat
                    fugiat non aliquip do laborum sint sint Lorem eu do. Et ut
                    duis irure laboris reprehenderit ea adipisicing amet
                    incididunt occaecat.
                  </p>
                </div>
              </div>
              <div className="p-5 rounded-xl bg-gradient-to-b from-purple-500 to-violet-500 text-white w-[225px] h-[250px] flex flex-col justify-around items-center gap-5 shadow-lg shadow-purple-300">
                <div>
                  <BsGraphUp size={55} className="mt-8" />
                </div>
                <div>
                  <p className="text-center mb-3 font-bold">Better Results</p>
                  <p className="text-[9px] leading-3 text-center text-white/75">
                    Commodo aliquip esse fugiat sint id enim officia. Amet non
                    id magna ut non deserunt magna Lorem aliqua. Proident
                    adipisicing dolor veniam incididunt reprehenderit eu
                    consequat excepteur exercitation .
                  </p>
                </div>
              </div>
              <div className="p-5 rounded-xl bg-gradient-to-b from-purple-500 to-violet-500 text-white w-[225px] h-[250px] flex flex-col justify-around items-center gap-5 shadow-lg shadow-purple-300">
                <div>
                  <GiTakeMyMoney size={55} className="mt-8" />
                </div>
                <div>
                  <p className="text-center mb-3 font-bold">Affordability</p>
                  <p className="text-[9px] leading-3 text-center text-white/75">
                    Nisi magna sunt enim veniam culpa ex excepteur ex cillum
                    elit adipisicing quis fugiat sit. Mollit dolore ad voluptate
                    incididunt. Veniam anim exercitation minim id proident. Do
                    in esse fugiat qui culpa labore laboris dolore amet mollit.
                  </p>
                </div>
              </div>
            </div>
          </section>
          <section className=" bg-gradient-to-r from-violet-500 to-pink-400 text-white">
            <div className="flex flex-col xl:px-24 lg:px-18 md:px-12 px-2 py-8 gap-5">
              <p className="text-3xl font-bold">1K+ Certified Tutors</p>
              <p className="text-sm text-white/60 lg:w-[45%] md:w-[75%] w-[100%]">
                Aliqua voluptate fugiat incididunt consectetur. Exercitation
                velit occaecat incididunt consequat culpa tempor in sit
                excepteur consectetur esse cupidatat nostrud labore.
              </p>
              <button className="border border-white rounded-3xl w-fit py-1 px-3 text-xs">
                Browse Subjects
              </button>
            </div>
          </section>
          <section
            id="footer"
            className="bg-black text-white py-12  xl:px-24 lg:px-18 md:px-12 px-2 flex flex-wrap md:gap-0"
          >
            <div className="w-2/6 hidden md:block p-2">
              <p className="text-[12px] font-bold">
                STARTING YOUR PREPARATION?
              </p>
              <p className="text-[8px] mt-8 w-[80%]">
                Simple classroom and the simpleclassroom logo are trade marks of
                Simple Classroom and are registered. Copyright 2022 Simple
                Classroom Limite. All rights reserved.
              </p>
            </div>
            <div className="md:w-1/6 w-2/4 p-2">
              <p className="text-[12px] font-bold">FOLLOW US</p>
              <div className="flex mt-6 gap-2">
                <FiInstagram />
                <FaFacebookF />
                <AiOutlineTwitter />
                <FaLinkedinIn />
              </div>
            </div>
            <div className="md:w-1/6 w-2/4 p-2">
              <p className="text-[12px] font-bold mb-6">
                ABOUT SIMPLE CLASSROOM
              </p>
              <p className="text-[10px] mt-3">Link 1</p>
              <p className="text-[10px] mt-3">Link 2</p>
              <p className="text-[10px] mt-3">Link 3</p>
            </div>
            <div className="md:w-1/6 w-2/4  p-2">
              <p className="text-[12px] font-bold mb-6">CUSTOMER SERVICE</p>
              <p className="text-[10px] mt-3">Link 1</p>
              <p className="text-[10px] mt-3">Link 2</p>
              <p className="text-[10px] mt-3">Link 3</p>
            </div>
            <div className="md:w-1/6 w-2/4 p-2">
              <p className="text-[12px] font-bold mb-6">HELP AND SUPPORT</p>
              <p className="text-[10px] mt-3">Link 1</p>
              <p className="text-[10px] mt-3">Link 2</p>
              <p className="text-[10px] mt-3">Link 3</p>
            </div>
          </section>
        </div>
      </main>
    </>
  );
}
